import type { User } from '../types'
import { hashPassword } from '../utils/auth'
import { nowIso } from '../utils/helpers'

export const SEED_USERS: User[] = [
  {
    id: 'usr_super',
    name: 'Admin Pertamina',
    email: 'admin@pertamina.id',
    passwordHash: hashPassword('admin123'),
    role: 'super_admin',
    teamId: null,
    departmentId: null,
    avatarColor: '#E31E24',
    active: true,
    createdAt: nowIso(),
    createdBy: null,
    lastLoginAt: null,
  },
  {
    id: 'usr_itd_lead',
    name: 'Aditya Pratama',
    email: 'aditya@pertamina.id',
    passwordHash: hashPassword('itd123'),
    role: 'team_admin',
    teamId: 'team_itd',
    departmentId: null,
    avatarColor: '#5b6af8',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_net_lead',
    name: 'Bayu Santoso',
    email: 'bayu@pertamina.id',
    passwordHash: hashPassword('net123'),
    role: 'team_admin',
    teamId: 'team_net',
    departmentId: null,
    avatarColor: '#8b5cf6',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_itd_kadep_be',
    name: 'Hendra Wijaya',
    email: 'hendra@pertamina.id',
    passwordHash: hashPassword('kadep123'),
    role: 'team_lead',
    teamId: 'team_itd',
    departmentId: 'dept_itd_backend',
    avatarColor: '#0891B2',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_itd_lead',
    lastLoginAt: null,
  },
  {
    id: 'usr_itd_member',
    name: 'Rina Wulandari',
    email: 'rina@pertamina.id',
    passwordHash: hashPassword('member123'),
    role: 'member',
    teamId: 'team_itd',
    departmentId: 'dept_itd_frontend',
    avatarColor: '#06b6d4',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_itd_lead',
    lastLoginAt: null,
  },
  {
    id: 'usr_itd_staff',
    name: 'Dimas Saputra',
    email: 'dimas@pertamina.id',
    passwordHash: hashPassword('staff123'),
    role: 'staff',
    teamId: 'team_itd',
    departmentId: 'dept_itd_backend',
    avatarColor: '#059669',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_itd_kadep_be',
    lastLoginAt: null,
  },
  {
    id: 'usr_biz_member',
    name: 'Sari Lestari',
    email: 'sari@pertamina.id',
    passwordHash: hashPassword('member123'),
    role: 'member',
    teamId: 'team_biz',
    departmentId: 'dept_biz_process_analysis',
    avatarColor: '#10b981',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_viewer',
    name: 'Tamu Direksi',
    email: 'tamu@pertamina.id',
    passwordHash: hashPassword('tamu123'),
    role: 'viewer',
    teamId: null,
    departmentId: null,
    avatarColor: '#64748b',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_admin_osm',
    name: 'Admin OSM',
    email: 'admin.osm@pertamina.id',
    passwordHash: hashPassword('osm123'),
    role: 'admin_osm',
    teamId: null,
    departmentId: null,
    avatarColor: '#0EA5E9',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_admin_dmo',
    name: 'Admin DMO',
    email: 'admin.dmo@pertamina.id',
    passwordHash: hashPassword('dmo123'),
    role: 'admin_dmo',
    teamId: null,
    departmentId: null,
    avatarColor: '#059669',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_admin_scs',
    name: 'Admin SCS',
    email: 'admin.scs@pertamina.id',
    passwordHash: hashPassword('scs123'),
    role: 'admin_scs',
    teamId: null,
    departmentId: null,
    avatarColor: '#D97706',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_doccon_osm',
    name: 'Doccon OSM',
    email: 'doccon.osm@pertamina.id',
    passwordHash: hashPassword('osm123'),
    role: 'doccon_osm',
    teamId: null,
    departmentId: null,
    avatarColor: '#8B5CF6',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_engineer_os',
    name: 'Engineer On Site',
    email: 'engineer.os@pertamina.id',
    passwordHash: hashPassword('eos123'),
    role: 'engineer_os',
    teamId: null,
    departmentId: null,
    avatarColor: '#F59E0B',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
  {
    id: 'usr_sales',
    name: 'Bayu Pratama',
    email: 'sales@pertamina.id',
    passwordHash: hashPassword('sales123'),
    role: 'sales',
    teamId: null,
    departmentId: null,
    avatarColor: '#10B981',
    active: true,
    createdAt: nowIso(),
    createdBy: 'usr_super',
    lastLoginAt: null,
  },
]
